"""The pre-commit comment gate: tracker references and the 2-line cap.

The engine reads a staged diff (`git diff --cached -U0`) plus the staged blob
of each changed file, so a block comment that began in unchanged lines is still
seen as a comment. Nothing here needs a forge or a tracker.
"""
from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
from pathlib import Path

import pytest

PLUGIN_ROOT = Path(__file__).resolve().parents[2]
ENGINE = PLUGIN_ROOT / "hooks" / "lib" / "comment_gate.py"


def load():
    spec = importlib.util.spec_from_file_location("comment_gate", ENGINE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


gate = load()


def check(path, before, after, *, tracker="jira", keys=""):
    """Findings for a change of one file, given its old and new text."""
    patterns = gate.load_reference_patterns(PLUGIN_ROOT, tracker, keys)
    old_lines = before.splitlines()
    new_lines = after.splitlines()
    added = [(number, text) for number, text in enumerate(new_lines, 1)
             if text not in old_lines]
    return gate.check_file(path, after, {number for number, _ in added}, patterns)


def messages(findings):
    return [finding.message for finding in findings]


def test_a_tracker_reference_in_a_line_comment_blocks():
    findings = check("src/App.java", "", "int a = 1; // PAY-142 keep this\n")
    assert len(findings) == 1
    assert "PAY-142" in findings[0].message
    assert findings[0].line == 1


def test_a_tracker_reference_inside_a_todo_still_blocks():
    findings = check("src/app.py", "", "# TODO(PAY-142): add the field\n")
    assert [finding.kind for finding in findings] == ["tracker"]


def test_a_todo_without_a_reference_passes():
    assert check("src/app.py", "", "# TODO: add the currency field\n") == []


def test_notation_prefixes_and_standard_names_are_not_tracker_references():
    text = "// UTF-8 bytes, SHA-256 digest, RFC-7231 date, ISO-8601\nint a;\n"
    assert check("src/App.java", "", text) == []


def test_three_consecutive_added_comment_lines_block():
    text = "// one\n// two\n// three\nint a;\n"
    findings = check("src/App.java", "", text)
    assert [finding.kind for finding in findings] == ["cap"]
    assert "3" in findings[0].message


def test_two_consecutive_added_comment_lines_pass():
    assert check("src/App.java", "", "// one\n// two\nint a;\n") == []


def test_block_comment_body_lines_count():
    text = "/*\n * one\n * two\n * three\n */\nint a;\n"
    findings = check("src/App.java", "", text)
    assert [finding.kind for finding in findings] == ["cap"]


def test_blank_comment_lines_neither_count_nor_break_a_run():
    text = "// one\n//\n// two\n//\n// three\nint a;\n"
    assert [finding.kind for finding in check("src/App.java", "", text)] == ["cap"]


def test_a_code_line_breaks_a_run():
    text = "// one\n// two\nint a;\n// three\n// four\n"
    assert check("src/App.java", "", text) == []


def test_only_added_lines_count_toward_the_cap():
    before = "// old one\n// old two\nint a;\n"
    after = "// old one\n// old two\n// new three\nint a;\n"
    assert check("src/App.java", before, after) == []


def test_doc_comments_are_exempt_from_the_cap():
    text = "/**\n * one\n * two\n * three\n * four\n */\nint a;\n"
    assert check("src/App.java", "", text) == []
    assert check("src/lib.rs", "", "/// one\n/// two\n/// three\nfn a() {}\n") == []


def test_a_tracker_reference_in_a_doc_comment_still_blocks():
    text = "/**\n * See PAY-142.\n */\nint a;\n"
    assert [finding.kind for finding in check("src/App.java", "", text)] == ["tracker"]


def test_license_header_and_generated_marker_are_exempt():
    header = ("/*\n * Copyright 2026 Example\n * Licensed under the Apache License\n"
              " * See the NOTICE file, ABC-123 form\n */\nint a;\n")
    assert check("src/App.java", "", header) == []
    generated = "// Code generated by tool. DO NOT EDIT.\n// source: ABC-123\n// more\npackage x\n"
    assert check("src/x.go", "", generated) == []


def test_tool_directives_are_exempt():
    text = "// eslint-disable-next-line no-console\n// @ts-expect-error TS-2345\n// prettier-ignore\nlet a\n"
    assert check("src/a.ts", "", text) == []
    assert check("src/a.py", "", "#!/usr/bin/env python3\n# noqa: E501\n# type: ignore\nx = 1\n") == []


def test_a_slash_pair_inside_a_string_is_not_a_comment():
    text = 'String u = "http://host/PAY-142";\n'
    assert check("src/App.java", "", text) == []


def test_a_block_comment_that_began_in_unchanged_lines_is_a_comment():
    before = "/*\n * old\n */\nint a;\n"
    after = "/*\n * old\n * PAY-142 added inside\n */\nint a;\n"
    findings = check("src/App.java", before, after)
    assert [finding.kind for finding in findings] == ["tracker"]


def test_hash_comment_needs_a_word_start():
    assert check("src/run.sh", "", 'echo "${#items} PAY-142"\n') == []
    assert [f.kind for f in check("src/run.sh", "", "echo hi # PAY-142 note\n")] == ["tracker"]


def test_python_docstring_is_a_string_not_a_comment():
    text = 'def f():\n    """One.\n\n    Two.\n    Three.\n    """\n'
    assert check("src/app.py", "", text) == []


def test_html_comments_are_checked():
    text = "<!-- one -->\n<!-- two -->\n<!-- three -->\n<div></div>\n"
    assert [finding.kind for finding in check("web/index.html", "", text)] == ["cap"]


def test_sql_dash_comments_are_checked():
    text = "-- one\n-- two\n-- three\nselect 1;\n"
    assert [finding.kind for finding in check("db/q.sql", "", text)] == ["cap"]


def test_github_tracker_forms_are_read_from_the_adapter_manifest():
    findings = check("src/App.java", "", "int a; // fixes #142\n", tracker="github-issues")
    assert [finding.kind for finding in findings] == ["tracker"]
    assert check("src/App.java", "", "int a; // fixes #142\n", tracker="jira") == []


def test_no_tracker_falls_back_to_the_shared_ticket_shape():
    assert [f.kind for f in check("src/App.java", "", "int a; // AB-12\n", tracker="none")] == ["tracker"]
    assert [f.kind for f in check("src/App.java", "", "int a; // AB-12\n", tracker="")] == ["tracker"]


def test_unknown_extensions_are_reported_unchecked_and_data_files_are_silent():
    assert gate.classify_path("notes/a.weird") == "unchecked"
    assert gate.classify_path("docs/a.md") == "skip"
    assert gate.classify_path("data/a.json") == "skip"
    assert gate.classify_path("src/App.java") == "checked"


# ---- the CLI over a real staged diff --------------------------------------

def git(cwd, *arguments):
    return subprocess.run(["git", *arguments], cwd=cwd, check=True, text=True,
                          capture_output=True).stdout


def init_repo(tmp_path):
    git(tmp_path, "init", "-q")
    git(tmp_path, "config", "user.name", "Gate Test")
    git(tmp_path, "config", "user.email", "gate@example.test")
    (tmp_path / "keep.txt").write_text("x\n", encoding="utf-8")
    git(tmp_path, "add", "keep.txt")
    git(tmp_path, "commit", "-qm", "base")


def run_cli(tmp_path, tracker="jira"):
    return subprocess.run(
        ["python", str(ENGINE), "--plugin-root", str(PLUGIN_ROOT), "--tracker", tracker],
        cwd=tmp_path, text=True, capture_output=True)


def test_cli_blocks_a_staged_tracker_reference_and_names_file_and_line(tmp_path):
    init_repo(tmp_path)
    (tmp_path / "App.java").write_text("class A {\n  int a; // PAY-142 why\n}\n", encoding="utf-8")
    git(tmp_path, "add", "App.java")
    done = run_cli(tmp_path)
    assert done.returncode == 2
    assert "App.java:2" in done.stderr
    assert "PAY-142" in done.stderr


def test_cli_passes_a_clean_staged_change_and_reports_unchecked_files(tmp_path):
    init_repo(tmp_path)
    (tmp_path / "App.java").write_text("class A {\n  int a;\n}\n", encoding="utf-8")
    (tmp_path / "odd.weird").write_text("// PAY-142\n", encoding="utf-8")
    git(tmp_path, "add", "App.java", "odd.weird")
    done = run_cli(tmp_path)
    assert done.returncode == 0
    assert "unchecked" in done.stderr
    assert "odd.weird" in done.stderr


def test_cli_only_judges_staged_bytes(tmp_path):
    init_repo(tmp_path)
    target = tmp_path / "App.java"
    target.write_text("class A {\n  int a;\n}\n", encoding="utf-8")
    git(tmp_path, "add", "App.java")
    target.write_text("class A {\n  int a; // PAY-142 unstaged\n}\n", encoding="utf-8")
    assert run_cli(tmp_path).returncode == 0


def test_cli_leaves_existing_comments_alone(tmp_path):
    init_repo(tmp_path)
    (tmp_path / "App.java").write_text("// PAY-142 old\n// two\n// three\nclass A {}\n",
                                       encoding="utf-8")
    git(tmp_path, "add", "App.java")
    git(tmp_path, "commit", "-qm", "old comments")
    (tmp_path / "App.java").write_text("// PAY-142 old\n// two\n// three\nclass A { int b; }\n",
                                       encoding="utf-8")
    git(tmp_path, "add", "App.java")
    assert run_cli(tmp_path).returncode == 0


def test_cli_json_output_lists_findings(tmp_path):
    init_repo(tmp_path)
    (tmp_path / "a.py").write_text("x = 1  # PAY-142\n", encoding="utf-8")
    git(tmp_path, "add", "a.py")
    done = subprocess.run(
        ["python", str(ENGINE), "--plugin-root", str(PLUGIN_ROOT), "--tracker", "jira", "--json"],
        cwd=tmp_path, text=True, capture_output=True)
    payload = json.loads(done.stdout)
    assert payload["findings"][0]["path"] == "a.py"
    assert payload["findings"][0]["kind"] == "tracker"


def test_a_shebang_line_is_a_directive_not_a_comment_line():
    assert check("bin/run.sh", "", "#!/usr/bin/env bash\n# one\n# two\necho hi\n") == []



# ---- the cap counts every added comment line -------------------------------

def test_three_adjacent_inline_comments_block():
    text = "int a; // one\nint b; // two\nint c; // three\n"
    assert [f.kind for f in check("src/App.java", "", text)] == ["cap"]


def test_three_adjacent_todo_comments_block_and_a_lone_todo_passes():
    text = "// TODO: one\n// TODO: two\n// TODO: three\nint a;\n"
    assert [f.kind for f in check("src/App.java", "", text)] == ["cap"]
    assert check("src/App.java", "", "// TODO: one\nint a;\n") == []


def test_two_inline_comments_pass():
    assert check("src/App.java", "", "int a; // one\nint b; // two\nint c;\n") == []


# ---- multi-line strings are code ---------------------------------------------

BODY = "  // PAY-142\n  // two\n  // three\n  "


@pytest.mark.parametrize("path,text", [
    ("src/A.java", 'String s = """\n' + BODY + '""";\n'),
    ("src/A.kt", 'val s = """\n' + BODY + '"""\n'),
    ("src/A.scala", 'val s = """\n' + BODY + '"""\n'),
    ("src/A.swift", 'let s = """\n' + BODY + '"""\n'),
    ("src/A.cs", 'var s = @"\n' + BODY + '";\n'),
    ("src/B.cs", 'var s = """\n' + BODY + '""";\n'),
    ("src/C.groovy", "def s = '''\n" + BODY + "'''\n"),
])
def test_comment_shaped_text_inside_a_multiline_string_is_not_a_comment(path, text):
    assert check(path, "", text) == []


def test_a_comment_after_a_closed_text_block_is_still_checked():
    text = 'String s = """\n  x\n  """; // PAY-142\n'
    assert [f.kind for f in check("src/A.java", "", text)] == ["tracker"]


def test_a_csharp_verbatim_string_treats_a_doubled_quote_as_an_escape():
    text = 'var s = @"a ""// PAY-142"" b";\nint x;\n'
    assert check("src/A.cs", "", text) == []


# ---- PowerShell block comments -------------------------------------------------

def test_powershell_block_comments_are_checked():
    tracker = "<#\n PAY-142 note\n#>\nGet-Item\n"
    assert [f.kind for f in check("tools/run.ps1", "", tracker)] == ["tracker"]
    cap = "<#\n one\n two\n three\n#>\nGet-Item\n"
    assert [f.kind for f in check("tools/run.ps1", "", cap)] == ["cap"]
    assert check("tools/run.ps1", "", "# one\n# two\nGet-Item\n") == []


# ---- the tracker key comes from the repository configuration ------------------

def test_a_configured_project_key_matches_only_that_key():
    text = "// see RFC-3339 and HTTP-2\n// key size RSA-2048, ARM-64, ES-2015\nint a;\n"
    assert check("src/A.java", "", text, keys="ABC") == []
    assert [f.kind for f in check("src/A.java", "", "int a; // ABC-12\n", keys="ABC")] == ["tracker"]
    assert check("src/A.java", "", "int a; // XYZ-12\n", keys="ABC") == []
    assert [f.kind for f in check("src/A.java", "", "int a; // XYZ-12\n", keys="ABC,XYZ")] == ["tracker"]


def test_without_a_configured_key_the_generic_shape_and_local_notation_apply():
    assert check("src/A.java", "", "// see RFC-3339 and HTTP-2\nint a;\n") == []
    assert [f.kind for f in check("src/A.java", "", "int a; // PAY-12\n")] == ["tracker"]


def test_cli_reads_the_project_keys_option(tmp_path):
    init_repo(tmp_path)
    (tmp_path / "A.java").write_text(
        "class A {\n  int a; // key size RSA-2048\n  int b; // ABC-12\n}\n", encoding="utf-8")
    git(tmp_path, "add", "A.java")
    done = subprocess.run(
        ["python", str(ENGINE), "--plugin-root", str(PLUGIN_ROOT), "--tracker", "jira",
         "--project-keys", "ABC"], cwd=tmp_path, text=True, capture_output=True)
    assert done.returncode == 2
    assert "A.java:3" in done.stderr and "A.java:2" not in done.stderr


def test_the_gate_wrapper_passes_the_configured_jira_project():
    wrapper = (PLUGIN_ROOT / "hooks" / "comment-gate.sh").read_text(encoding="utf-8")
    assert "AFK_CFG_JIRA_PROJECT" in wrapper


def test_comment_notation_stays_out_of_the_shared_redaction_list():
    shared = gate._tsv(PLUGIN_ROOT)["notation-prefixes"].split("|")
    assert not {"MD", "SHA", "HTTP", "RSA"} & set(shared)


# ---- round 3: real delimiter rules -------------------------------------------

BS = chr(92)


def test_java_text_block_with_an_escaped_delimiter_stays_a_string():
    text = ('String s = """\n'
            '  say ' + BS + '""" // PAY-123\n'
            '  // two\n  // three\n  """;\n')
    assert check("src/A.java", "", text) == []


def test_kotlin_raw_string_ends_at_the_first_delimiter_even_after_a_backslash():
    text = 'val s = """C:' + BS + '"""\n// PAY-123\n'
    assert [f.kind for f in check("src/A.kt", "", text)] == ["tracker"]


def test_csharp_raw_string_closes_only_on_its_own_quote_count():
    text = ('var s = """"\n'
            '  has """ inside // PAY-123\n'
            '  // two\n  // three\n  """";\n')
    assert check("src/A.cs", "", text) == []
    after = 'var s = """"\n  x\n  """"; // PAY-123\n'
    assert [f.kind for f in check("src/A.cs", "", after)] == ["tracker"]


def test_csharp_interpolated_raw_string_is_a_string():
    text = 'var s = $$"""\n  {{x}} // PAY-123\n  """;\n'
    assert check("src/A.cs", "", text) == []


@pytest.mark.parametrize("quote", ['"', "'"])
def test_powershell_here_string_is_a_string(quote):
    text = ("$s = @" + quote + "\n# PAY-123\n# two\n# three\n" + quote + "@\n# real PAY-9\n")
    findings = check("tools/run.ps1", "", text)
    assert [(f.kind, f.line) for f in findings] == [("tracker", 6)]


def test_powershell_here_string_closes_only_at_the_line_start():
    text = '$s = @"\n  "@ not a close // x\n# PAY-123\n"@\n'
    assert check("tools/run.ps1", "", text) == []


# ---- round 3: directives never hide a tracker reference ------------------------

@pytest.mark.parametrize("comment", [
    "// This region fixes PAY-123",
    "// the pragma from PAY-123",
    "// eslint-disable-next-line no-console -- PAY-123",
    "// noqa PAY-123",
    "// region PAY-123",
])
def test_a_tracker_reference_is_blocked_beside_or_inside_a_directive_word(comment):
    assert [f.kind for f in check("src/A.java", "", comment + "\nint a;\n")] == ["tracker"]


def test_a_word_inside_a_sentence_is_not_a_directive():
    text = "// This region is fixed\n// the pragma is here\n// and more\nint a;\n"
    assert [f.kind for f in check("src/A.java", "", text)] == ["cap"]


def test_real_directives_stay_exempt_from_the_cap():
    text = "// eslint-disable-next-line a\n// prettier-ignore\n// @ts-expect-error\nlet a\n"
    assert check("src/a.ts", "", text) == []
    assert check("src/A.cs", "", "// region Setup\n// endregion\n// region Other\nint a;\n") == []


# ---- round 4: code inside interpolation holes ---------------------------------

def hits(path, text):
    return [(f.kind, f.line) for f in check(path, "", text)]


PS_HOLE = '$s = @"\nvalue $(1 + 1 # PAY-123\n)\n"@\n$s\n'


def test_powershell_subexpression_in_an_expandable_here_string_is_code():
    assert hits("tools/run.ps1", PS_HOLE) == [("tracker", 2)]


def test_powershell_fixture_is_real_code_for_the_native_parser(tmp_path):
    shell = shutil.which("pwsh")
    if not shell:
        pytest.skip("pwsh is not installed")
    script = tmp_path / "fixture.ps1"
    script.write_text(PS_HOLE, encoding="utf-8")
    probe = ("$t=$null;$e=$null;"
             f"[void][System.Management.Automation.Language.Parser]::ParseFile('{script}',[ref]$t,[ref]$e);"
             f"($t.NestedTokens | Where-Object {{ $_.Kind -eq 'Comment' }}).Text; & '{script}'")
    run = subprocess.run([shell, "-NoProfile", "-Command", probe],
                         capture_output=True, text=True, timeout=120)
    assert "PAY-123" in run.stdout
    assert "value 2" in run.stdout


def test_powershell_nested_parentheses_strings_and_block_comments_in_a_subexpression():
    text = ('$s = @"\n'
            'a $(\n'
            '  Get-Thing ( 1 + (2) )  # PAY-123\n'
            '  "text with ) and # inside"\n'
            '  <# PAY-456 #>\n'
            ')\n'
            'tail # PAY-9 stays text\n'
            '"@\n')
    assert hits("tools/run.ps1", text) == [("tracker", 3), ("tracker", 5)]


def test_powershell_single_quoted_here_string_stays_literal():
    text = "$s = @'\n$(1 # PAY-123\n)\n'@\n"
    assert hits("tools/run.ps1", text) == []


def test_powershell_escaped_subexpression_is_not_a_hole():
    text = '$s = @"\n`$(1 # PAY-123\n"@\n'
    assert hits("tools/run.ps1", text) == []


def test_powershell_here_string_closes_after_its_subexpression_ends():
    text = '$s = @"\n$(1)\n"@\n# real PAY-9\n'
    assert hits("tools/run.ps1", text) == [("tracker", 4)]


def test_kotlin_template_expression_in_a_raw_string_is_code():
    text = 'val s = """\n  a ${\n    x // PAY-123\n  }\n"""\n'
    assert hits("src/A.kt", text) == [("tracker", 3)]


def test_kotlin_template_block_comment_and_nested_braces_and_strings():
    text = ('val s = """\n'
            '  ${ /* PAY-123 */ x }\n'
            '  ${ map { "}" } // PAY-456\n'
            '  }\n'
            '  after // PAY-9 is text\n'
            '"""\n')
    assert hits("src/A.kt", text) == [("tracker", 2), ("tracker", 3)]


def test_kotlin_raw_string_text_outside_a_hole_stays_a_string():
    assert hits("src/A.kt", 'val s = """http://x ${a} // PAY-9\n"""\n') == []


def test_scala_interpolated_triple_quotes_have_holes_and_plain_ones_do_not():
    assert hits("src/A.scala", 'val s = s"""\n${x // PAY-123\n}\n"""\n') == [("tracker", 2)]
    assert hits("src/A.scala", 'val s = """\n${x // PAY-123\n"""\n') == []


def test_java_text_block_has_no_holes():
    assert hits("src/A.java", 'String s = """\n  ${x // PAY-123\n  """;\n') == []


def test_csharp_interpolated_raw_string_hole_is_code():
    text = 'var s = $"""\n  v {x // PAY-123\n  } end\n  """;\n'
    assert hits("src/A.cs", text) == [("tracker", 2)]


def test_csharp_hole_needs_as_many_braces_as_dollars():
    literal = 'var s = $$"""\n  {\n  // PAY-9\n  """;\n'
    assert hits("src/A.cs", literal) == []
    text = 'var s = $$"""\n  {{ x /* PAY-123 */ }}\n  {{ y // PAY-456\n  }} tail // PAY-7\n  """;\n'
    assert hits("src/A.cs", text) == [("tracker", 2), ("tracker", 3)]


def test_csharp_plain_raw_string_has_no_holes_and_hole_close_returns_to_the_string():
    assert hits("src/A.cs", 'var s = """\n  {x // PAY-123\n  """;\n') == []
    assert hits("src/A.cs", 'var s = $"""\n {a} // PAY-123\n """;\n') == []


# ---- round 5: nested holes, backtick parity, Scala dollar escapes -------------

PS_WALK = ("function Walk($tokens) { foreach ($t in $tokens) { $t; "
           "if ($t.NestedTokens) { Walk $t.NestedTokens } } }; ")


def powershell_comments(tmp_path, text):
    """Parse errors and comment texts the native PowerShell parser finds in `text`."""
    shell = shutil.which("pwsh")
    if not shell:
        pytest.skip("pwsh is not installed")
    script = tmp_path / "fixture.ps1"
    script.write_text(text, encoding="utf-8")
    probe = (PS_WALK + "$t=$null;$e=$null;"
             f"[void][System.Management.Automation.Language.Parser]::ParseFile('{script}',[ref]$t,[ref]$e);"
             "'ERRORS=' + $e.Count; "
             f"Walk $t | Where-Object {{ $_.Kind -eq 'Comment' }} | ForEach-Object {{ 'COMMENT=' + $_.Text }}")
    run = subprocess.run([shell, "-NoProfile", "-Command", probe],
                         capture_output=True, text=True, timeout=120)
    lines = run.stdout.splitlines()
    errors = int(next(line for line in lines if line.startswith("ERRORS=")).split("=")[1])
    return errors, [line[len("COMMENT="):] for line in lines if line.startswith("COMMENT=")]


BT = chr(96)
PS_NESTED = '$s = @"\n$( "value $(1 # PAY-123\n)" )\n"@\n'
PS_EVEN = '$s = @"\n' + BT * 2 + '$(1 # PAY-123\n)\n"@\n'
PS_ODD = '$s = @"\n' + BT * 3 + '$(1 # PAY-123\n"@\n'


@pytest.mark.parametrize("name, text, flagged", [
    ("a subexpression inside a quoted string inside a hole", PS_NESTED, True),
    ("two backticks leave the hole open", PS_EVEN, True),
    ("three backticks escape the hole", PS_ODD, False),
])
def test_powershell_holes_agree_with_the_native_parser(tmp_path, name, text, flagged):
    errors, comments = powershell_comments(tmp_path, text)
    assert errors == 0
    assert any("PAY-123" in c for c in comments) is flagged
    assert (hits("tools/run.ps1", text) == [("tracker", 2)]) is flagged


def test_powershell_single_quoted_string_in_a_hole_stays_literal():
    text = '$s = @"\n$( \'value $(1 # PAY-123\' )\n"@\n'
    assert hits("tools/run.ps1", text) == []


def test_powershell_nested_subexpression_closes_back_into_its_string():
    text = '$s = @"\n$( "a $(1) b" ) # PAY-9 is text\n"@\n# real PAY-8\n'
    assert hits("tools/run.ps1", text) == [("tracker", 4)]


def test_scala_double_dollar_is_a_literal_dollar_not_a_hole():
    assert hits("src/A.scala", 's"""\n$${notCode // PAY-123\n}\n"""\n') == []
    assert hits("src/A.scala", 's"""\n$$$${notCode // PAY-123\n}\n"""\n') == []


def test_scala_odd_dollar_run_ends_in_a_hole():
    assert hits("src/A.scala", 's"""\n$$${code // PAY-123\n}\n"""\n') == [("tracker", 2)]
    assert hits("src/A.scala", 's"""\n${code // PAY-123\n}\n"""\n') == [("tracker", 2)]
