#!/usr/bin/env python3
"""
publish_prd.py — deterministically publish a PRD.md into a Jira Cloud issue.

This is the engine behind /afk:to-ticket. It does the parts that must be
byte-for-byte reproducible rather than eyeballed each run:

  1. Render every ```mermaid fenced block to a PNG locally (mmdc), so no
     diagram source ever leaves the network.
  2. Convert the PRD Markdown to ADF (Atlassian Document Format) via a fixed
     element mapping (see md_to_adf below).
  3. Upload each rendered PNG as an attachment, resolve its media UUID via the
     attachment content-URL 303 redirect, and embed it inline as an ADF media
     node (the only method Jira Cloud actually renders inline — verified
     against a real ticket; collection="" works).
  4. Merge into the issue description: the PRD lives inside an AFK-managed block
     delimited by sentinel marker paragraphs. Everything OUTSIDE that block
     (product-owner prose) is preserved verbatim. If the pre-existing
     description is barebone/low-value, the managed block becomes the whole
     description.
  5. Re-running is idempotent: the prior managed block + prior afk-* figure
     attachments are replaced, not duplicated.

Only PRD content is published. SDD / ADR / lower-level technical detail is the
caller's responsibility to keep out of PRD.md — this script publishes whatever
PRD.md contains, nothing more.

Usage:
    python publish_prd.py --parent P2P-1220 --prd path/to/PRD.md [--dry-run] [--yes]

Credentials are read from the Jira MCP server's env block in ~/.claude.json
(JIRA_BASE_URL / JIRA_EMAIL / JIRA_API_TOKEN), or from same-named OS env vars
if those are set (env vars win). Nothing is hardcoded.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import struct
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

from markdown_it import MarkdownIt

# ----------------------------------------------------------------------------
# Managed-block sentinels. These delimit the region this script owns inside the
# issue description. Edits BETWEEN the markers are overwritten on re-run; edits
# OUTSIDE are preserved verbatim. The text is matched exactly on re-run, so do
# not change it without a migration.
# ----------------------------------------------------------------------------
MARK_START = "afk:prd:start"
MARK_END = "afk:prd:end"
START_NOTE = (
    "  — auto-generated by /afk:to-ticket from PRD.md. "
    "Edits between this marker and afk:prd:end are overwritten on re-run; "
    "edit PRD.md and re-run instead."
)
FIG_PREFIX = "afk-fig"  # attachment filenames: afk-fig{N}.png


# ============================================================================
# Credentials
# ============================================================================
def _walk_for_jira_env(obj):
    if isinstance(obj, dict):
        jira = obj.get("jira")
        if isinstance(jira, dict) and isinstance(jira.get("env"), dict):
            return jira["env"]
        for v in obj.values():
            r = _walk_for_jira_env(v)
            if r:
                return r
    return None


def load_creds():
    base = os.environ.get("JIRA_BASE_URL")
    email = os.environ.get("JIRA_EMAIL")
    token = os.environ.get("JIRA_API_TOKEN")
    if not (base and email and token):
        cfg_path = Path.home() / ".claude.json"
        env = None
        if cfg_path.exists():
            env = _walk_for_jira_env(json.loads(cfg_path.read_text(encoding="utf-8")))
        if env:
            base = base or env.get("JIRA_BASE_URL")
            email = email or env.get("JIRA_EMAIL")
            token = token or env.get("JIRA_API_TOKEN")
    if not (base and email and token):
        sys.exit("ERROR: could not resolve Jira creds (JIRA_BASE_URL/EMAIL/API_TOKEN "
                 "from env or ~/.claude.json mcpServers.jira.env).")
    return base.rstrip("/"), email, token


class Jira:
    def __init__(self, base, email, token):
        self.base = base
        self.auth = "Basic " + base64.b64encode(f"{email}:{token}".encode()).decode()

    def _req(self, method, path, data=None, headers=None, follow=True):
        url = path if path.startswith("http") else self.base + path
        h = {"Authorization": self.auth, "Accept": "application/json"}
        if headers:
            h.update(headers)
        req = urllib.request.Request(url, data=data, method=method, headers=h)
        if follow:
            return urllib.request.urlopen(req, timeout=60)
        opener = urllib.request.build_opener(_NoRedirect)
        return opener.open(req, timeout=60)

    def get_issue(self, key, fields):
        r = self._req("GET", f"/rest/api/3/issue/{key}?fields={fields}")
        return json.loads(r.read())

    def update_description(self, key, adf):
        # notifyUsers=false would suppress watcher notifications, but Jira only
        # honours it for project/system admins (else 403), so we don't send it.
        body = json.dumps({"fields": {"description": adf}}).encode()
        self._req("PUT", f"/rest/api/3/issue/{key}", data=body,
                  headers={"Content-Type": "application/json"})

    def delete_attachment(self, att_id):
        try:
            self._req("DELETE", f"/rest/api/3/attachment/{att_id}")
        except urllib.error.HTTPError as e:
            if e.code not in (204, 200, 404):
                raise

    def upload_attachment(self, key, filepath):
        """Multipart upload. Returns the attachment id (str)."""
        boundary = "----afkPrdBoundary7MA4YWxkTrZu0gW"
        fname = os.path.basename(filepath)
        with open(filepath, "rb") as f:
            payload = f.read()
        body = b"".join([
            f"--{boundary}\r\n".encode(),
            f'Content-Disposition: form-data; name="file"; filename="{fname}"\r\n'.encode(),
            b"Content-Type: image/png\r\n\r\n",
            payload, b"\r\n",
            f"--{boundary}--\r\n".encode(),
        ])
        r = self._req("POST", f"/rest/api/3/issue/{key}/attachments", data=body,
                      headers={"X-Atlassian-Token": "no-check",
                               "Content-Type": f"multipart/form-data; boundary={boundary}"})
        arr = json.loads(r.read())
        return arr[0]["id"]

    def resolve_media_uuid(self, att_id):
        """GET attachment content, do NOT follow the 303; pull the UUID out of
        the api.media.atlassian.com/file/{uuid}/binary Location header."""
        try:
            r = self._req("GET", f"/rest/api/3/attachment/content/{att_id}", follow=False)
            loc = r.headers.get("Location", "")
        except urllib.error.HTTPError as e:
            loc = e.headers.get("Location", "")
        m = re.search(r"/file/([0-9a-fA-F-]{36})", loc)
        if not m:
            raise RuntimeError(f"could not resolve media UUID for attachment {att_id} "
                               f"(Location={loc!r})")
        return m.group(1)


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *a, **k):
        return None


# ============================================================================
# PNG dimensions (read IHDR)
# ============================================================================
def png_size(path):
    with open(path, "rb") as f:
        head = f.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    w, h = struct.unpack(">II", head[16:24])
    return int(w), int(h)


# ============================================================================
# Mermaid rendering
# ============================================================================
def render_mermaid(source, out_png):
    """Render a mermaid source string to out_png via mmdc / npx mermaid-cli."""
    with tempfile.NamedTemporaryFile("w", suffix=".mmd", delete=False, encoding="utf-8") as t:
        t.write(source)
        mmd = t.name
    cmds = [
        ["mmdc", "-i", mmd, "-o", out_png, "-b", "white"],
        ["npx", "-y", "@mermaid-js/mermaid-cli", "-i", mmd, "-o", out_png, "-b", "white"],
    ]
    last = None
    for cmd in cmds:
        try:
            subprocess.run(cmd, check=True, capture_output=True, text=True, shell=(os.name == "nt"))
            os.unlink(mmd)
            return out_png
        except FileNotFoundError as e:
            last = e
        except subprocess.CalledProcessError as e:
            last = e
            break
    os.unlink(mmd)
    raise RuntimeError(
        "mermaid render failed. Install mermaid-cli (npm i -g @mermaid-js/mermaid-cli) "
        f"or ensure npx can fetch it. Last error: {getattr(last,'stderr',last)}")


# ============================================================================
# Markdown -> ADF
# ============================================================================
MERMAID_RE = re.compile(r"^[ \t]*```+[ \t]*mermaid[ \t]*\n(.*?)\n[ \t]*```+[ \t]*$",
                        re.DOTALL | re.MULTILINE)
# Placeholder inserted in place of a mermaid block. Plain ASCII so CommonMark
# does not rewrite it (it replaces U+0000 with U+FFFD, so null sentinels break).
FIG_TOKEN = "AFKMERMAIDFIGURE{}ENDFIGURE"


def extract_mermaid(md_text):
    """Replace each ```mermaid block with a lone-paragraph placeholder token.
    Returns (new_md, [mermaid_source, ...]) in document order."""
    blocks = []

    def repl(m):
        idx = len(blocks)
        blocks.append(m.group(1))
        return f"\n\n{FIG_TOKEN.format(idx)}\n\n"

    return MERMAID_RE.sub(repl, md_text), blocks


def _inline_to_adf(token):
    """Convert one markdown-it `inline` token's children to ADF inline nodes."""
    out = []
    marks = []

    def push_text(text):
        if not text:
            return
        node = {"type": "text", "text": text}
        if marks:
            node["marks"] = [dict(m) for m in marks]
        out.append(node)

    for c in token.children or []:
        t = c.type
        if t == "text":
            push_text(c.content)
        elif t == "code_inline":
            node = {"type": "text", "text": c.content,
                    "marks": [dict(m) for m in marks] + [{"type": "code"}]}
            out.append(node)
        elif t == "strong_open":
            marks.append({"type": "strong"})
        elif t == "strong_close":
            _pop(marks, "strong")
        elif t == "em_open":
            marks.append({"type": "em"})
        elif t == "em_close":
            _pop(marks, "em")
        elif t == "s_open":
            marks.append({"type": "strike"})
        elif t == "s_close":
            _pop(marks, "strike")
        elif t == "link_open":
            href = dict(c.attrs).get("href", "")
            marks.append({"type": "link", "attrs": {"href": href}})
        elif t == "link_close":
            _pop(marks, "link")
        elif t == "softbreak":
            push_text(" ")
        elif t == "hardbreak":
            out.append({"type": "hardBreak"})
        elif t == "image":
            # rare in a PRD; degrade to the alt text as plain text
            push_text(c.content or dict(c.attrs).get("alt", "") or "[image]")
        # unknown inline types are dropped deterministically
    return out or [{"type": "text", "text": ""}]


def _pop(marks, mtype):
    for i in range(len(marks) - 1, -1, -1):
        if marks[i]["type"] == mtype:
            marks.pop(i)
            return


def md_to_adf_content(md_text, fig_nodes):
    """Return an ADF content array (list of block nodes). fig_nodes maps
    placeholder index -> media block node (already built)."""
    md = MarkdownIt("gfm-like", {"linkify": False, "html": False})
    tokens = md.parse(md_text)
    content, _ = _build_blocks(tokens, 0, None, fig_nodes)
    return content


def _build_blocks(tokens, i, stop, fig_nodes):
    """Build a list of block nodes until a `stop` close-token is hit.
    Returns (nodes, next_index)."""
    nodes = []
    while i < len(tokens):
        tok = tokens[i]
        t = tok.type
        if stop and t == stop:
            return nodes, i + 1

        if t == "heading_open":
            level = int(tok.tag[1])
            inline = tokens[i + 1]
            nodes.append({"type": "heading", "attrs": {"level": level},
                          "content": _inline_to_adf(inline)})
            i += 3  # open, inline, close
        elif t == "paragraph_open":
            inline = tokens[i + 1]
            text = inline.content.strip()
            m = re.fullmatch(r"AFKMERMAIDFIGURE(\d+)ENDFIGURE", text)
            if m:  # a mermaid placeholder paragraph -> media block(s)
                nodes.extend(fig_nodes.get(int(m.group(1)), []))
            else:
                nodes.append({"type": "paragraph", "content": _inline_to_adf(inline)})
            i += 3
        elif t == "bullet_list_open":
            children, i = _build_list_items(tokens, i + 1, "bullet_list_close", fig_nodes)
            nodes.append({"type": "bulletList", "content": children})
        elif t == "ordered_list_open":
            attrs = dict(tok.attrs)
            node = {"type": "orderedList", "content": None}
            if "start" in attrs and str(attrs["start"]) != "1":
                node["attrs"] = {"order": int(attrs["start"])}
            children, i = _build_list_items(tokens, i + 1, "ordered_list_close", fig_nodes)
            node["content"] = children
            nodes.append(node)
        elif t == "blockquote_open":
            children, i = _build_blocks(tokens, i + 1, "blockquote_close", fig_nodes)
            nodes.append({"type": "blockquote", "content": children})
        elif t == "hr":
            nodes.append({"type": "rule"})
            i += 1
        elif t == "fence" or t == "code_block":
            attrs = {}
            lang = (tok.info or "").strip().split()[0] if tok.info else ""
            if lang:
                attrs["language"] = lang
            node = {"type": "codeBlock", "content": [{"type": "text", "text": tok.content.rstrip("\n")}]}
            if attrs:
                node["attrs"] = attrs
            nodes.append(node)
            i += 1
        elif t == "table_open":
            node, i = _build_table(tokens, i + 1, fig_nodes)
            nodes.append(node)
        else:
            i += 1  # skip tokens we don't map (e.g. stray inline)
    return nodes, i


def _build_list_items(tokens, i, stop, fig_nodes):
    items = []
    while i < len(tokens):
        if tokens[i].type == stop:
            return items, i + 1
        if tokens[i].type == "list_item_open":
            children, i = _build_blocks(tokens, i + 1, "list_item_close", fig_nodes)
            if not children:
                children = [{"type": "paragraph", "content": [{"type": "text", "text": ""}]}]
            items.append({"type": "listItem", "content": children})
        else:
            i += 1
    return items, i


def _build_table(tokens, i, fig_nodes):
    rows = []
    is_header_section = False
    while i < len(tokens):
        t = tokens[i].type
        if t == "table_close":
            i += 1
            break
        if t == "thead_open":
            is_header_section = True
            i += 1
        elif t == "thead_close":
            is_header_section = False
            i += 1
        elif t == "tbody_open" or t == "tbody_close":
            i += 1
        elif t == "tr_open":
            cells = []
            i += 1
            while tokens[i].type != "tr_close":
                ct = tokens[i].type
                if ct in ("th_open", "td_open"):
                    cell_type = "tableHeader" if ct == "th_open" else "tableCell"
                    inline = tokens[i + 1]
                    cells.append({"type": cell_type, "attrs": {},
                                  "content": [{"type": "paragraph",
                                               "content": _inline_to_adf(inline)}]})
                    i += 3  # open, inline, close
                else:
                    i += 1
            rows.append({"type": "tableRow", "content": cells})
            i += 1  # skip tr_close
        else:
            i += 1
    return {"type": "table", "attrs": {"isNumberColumnEnabled": False, "layout": "default"},
            "content": rows}, i


# ============================================================================
# Description merge (preserve PO content, manage only the sentinel block)
# ============================================================================
def node_text(node):
    if isinstance(node, dict):
        if node.get("type") == "text":
            return node.get("text", "")
        return "".join(node_text(c) for c in node.get("content", []) or [])
    if isinstance(node, list):
        return "".join(node_text(c) for c in node)
    return ""


def is_start_marker(node):
    return (node.get("type") == "paragraph"
            and node_text(node).strip().startswith(MARK_START))


def is_end_marker(node):
    return (node.get("type") == "paragraph"
            and node_text(node).strip() == MARK_END)


def strip_managed_block(content):
    """Remove [start_marker .. end_marker] inclusive. Returns (remainder, insert_index).
    insert_index is where the block used to be (or len(remainder) if absent)."""
    out, i, insert_at = [], 0, None
    while i < len(content):
        if is_start_marker(content[i]):
            insert_at = len(out)
            j = i + 1
            while j < len(content) and not is_end_marker(content[j]):
                j += 1
            i = j + 1  # skip end marker too
            continue
        out.append(content[i])
        i += 1
    return out, (insert_at if insert_at is not None else len(out))


PLACEHOLDER_RE = re.compile(r"^(tbd|todo|n/?a|none|see prd|to be (defined|determined)|\.+)$", re.I)


def is_barebone(remainder):
    """Heuristic: True if the non-managed remainder is low-value and safe to absorb."""
    if not remainder:
        return True
    rich = {"table", "mediaSingle", "media", "mediaGroup", "codeBlock", "rule"}
    headings = sum(1 for n in remainder if n.get("type") == "heading")
    list_items = 0
    for n in remainder:
        if n.get("type") in ("bulletList", "orderedList"):
            list_items += len(n.get("content", []) or [])
        if n.get("type") in rich:
            return False
    if headings >= 2 or list_items >= 3:
        return False
    text = node_text(remainder).strip()
    if PLACEHOLDER_RE.fullmatch(text):
        return True
    return len(text) < 200


def marker_paragraph(text):
    return {"type": "paragraph",
            "content": [{"type": "text", "text": text, "marks": [{"type": "em"}]}]}


def build_description(existing_adf, prd_content):
    existing = (existing_adf or {}).get("content", []) if isinstance(existing_adf, dict) else []
    remainder, insert_at = strip_managed_block(existing)
    managed = [marker_paragraph(MARK_START + START_NOTE), *prd_content, marker_paragraph(MARK_END)]
    if is_barebone(remainder):
        final = managed
        absorbed = bool(remainder)
    elif insert_at == len(remainder):
        # No prior managed block: append at the end, separated by a rule so the
        # PO's content and the generated PRD are visually distinct.
        final = remainder + [{"type": "rule"}] + managed
        absorbed = False
    else:
        # Re-run: drop the managed block back where it was (the separating rule,
        # if any, lives in `remainder` outside the markers and is preserved).
        final = remainder[:insert_at] + managed + remainder[insert_at:]
        absorbed = False
    return {"version": 1, "type": "doc", "content": final}, absorbed, len(remainder)


# ============================================================================
# Main
# ============================================================================
def main():
    ap = argparse.ArgumentParser(description="Publish a PRD.md into a Jira issue (ADF).")
    ap.add_argument("--parent", required=True, help="Jira parent key, e.g. P2P-1220")
    ap.add_argument("--prd", required=True, help="path to PRD.md")
    ap.add_argument("--dry-run", action="store_true",
                    help="convert + plan only; render no diagrams, mutate nothing, print ADF")
    ap.add_argument("--yes", action="store_true", help="skip the confirmation prompt")
    args = ap.parse_args()

    prd_path = Path(args.prd)
    if not prd_path.exists():
        sys.exit(f"ERROR: PRD not found: {prd_path}")
    md_text = prd_path.read_text(encoding="utf-8")
    md_text, mermaid_blocks = extract_mermaid(md_text)

    base, email, token = load_creds()
    jira = Jira(base, email, token)

    # Fetch existing description + attachments first (also validates the parent + type).
    issue = jira.get_issue(args.parent, "summary,issuetype,description,attachment")
    itype = issue["fields"]["issuetype"]["name"]
    if itype not in ("Enhancement", "Bug"):
        sys.exit(f"ERROR: parent {args.parent} is a {itype!r}; expected Enhancement or Bug.")
    existing_desc = issue["fields"].get("description")
    existing_atts = issue["fields"].get("attachment", []) or []

    fig_nodes = {}  # placeholder idx -> [mediaSingle node]
    if args.dry_run:
        for idx in range(len(mermaid_blocks)):
            fig_nodes[idx] = [{"type": "paragraph", "content": [
                {"type": "text", "text": f"[dry-run: mermaid figure {idx+1} would render+attach here]",
                 "marks": [{"type": "em"}]}]}]
    else:
        # Replace prior afk-fig* attachments so re-runs don't pile up.
        fig_re = re.compile(rf"^{re.escape(FIG_PREFIX)}\d+\.png$")
        for a in existing_atts:
            if fig_re.match(a.get("filename", "")):
                jira.delete_attachment(a["id"])
        with tempfile.TemporaryDirectory() as td:
            for idx, src in enumerate(mermaid_blocks):
                png = os.path.join(td, f"{FIG_PREFIX}{idx+1}.png")
                render_mermaid(src, png)
                size = png_size(png) or (800, 600)
                att_id = jira.upload_attachment(args.parent, png)
                media_uuid = jira.resolve_media_uuid(att_id)
                fig_nodes[idx] = [{
                    "type": "mediaSingle", "attrs": {"layout": "center"},
                    "content": [{"type": "media", "attrs": {
                        "type": "file", "id": media_uuid, "collection": "",
                        "width": size[0], "height": size[1]}}],
                }]
                print(f"  figure {idx+1}: attached {FIG_PREFIX}{idx+1}.png "
                      f"({size[0]}x{size[1]}) -> media {media_uuid}")

    prd_content = md_to_adf_content(md_text, fig_nodes)
    new_desc, absorbed, kept = build_description(existing_desc, prd_content)

    print(f"\nparent      : {args.parent} ({itype}) — {issue['fields']['summary']}")
    print(f"PRD source  : {prd_path}")
    print(f"diagrams    : {len(mermaid_blocks)}")
    print(f"existing PO : {'absorbed (barebone)' if absorbed else f'{kept} node(s) preserved'}")
    print(f"ADF blocks  : {len(new_desc['content'])}")

    if args.dry_run:
        out = prd_path.with_suffix(".adf.json")
        out.write_text(json.dumps(new_desc, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"\n[dry-run] wrote ADF to {out} — nothing mutated.")
        return

    if not args.yes:
        ans = input("\nPUT this description to the issue? [y/N] ").strip().lower()
        if ans != "y":
            sys.exit("aborted.")
    jira.update_description(args.parent, new_desc)
    print(f"\nDONE: {args.parent} description updated.")


if __name__ == "__main__":
    main()
