#!/usr/bin/env python3
"""
publish_prd.py — deterministically publish a PRD.md into a Jira Cloud issue.

This is the engine behind /afk-toolkit:to-ticket. It does the parts that must be
byte-for-byte reproducible rather than eyeballed each run:

  1. Render every ```mermaid fenced block to a PNG locally (mmdc), so no
     diagram source ever leaves the network.
  2. Convert the PRD Markdown to ADF (Atlassian Document Format) via a fixed
     element mapping (see the tracker adapter's md_to_adf_content).
  3. Upload each rendered PNG as an attachment, resolve its media UUID via the
     attachment content-URL 303 redirect, and embed it inline as an ADF media
     node (the only method Jira Cloud actually renders inline — verified
     against a real ticket; collection="" works).
  4. Merge into the issue description: the PRD lives inside an AFK-managed block
     delimited by sentinel marker paragraphs. Everything OUTSIDE that block
     (product-owner prose) is preserved verbatim. If the pre-existing
     description is barebone/low-value, the managed block becomes the whole
     description.
  5. Re-running is idempotent: the prior managed block + prior afk-* figure
     attachments are replaced, not duplicated. A re-publish may carry --changes,
     a markdown requirements delta posted as an issue comment after the PUT so
     the change history stays trackable (skipped on a first publish).

The reusable Jira machinery — creds resolution, the REST client, Markdown→ADF
conversion, attachment upload + media-UUID extraction, PNG sizing — lives in the
configured tracker adapter (`adapters/tracker/<kind>/api.py`). This script keeps only
the PRD-specific concerns: mermaid rendering and the sentinel-block description
merge.

This script publishes whatever the --prd markdown file contains, nothing more.
Keeping the content at the right level (the skill's requirements-level TICKET.md
distillation — no SDD / ADR / technical detail, no repo-artifact references) is
the caller's responsibility.

Usage:
    python publish_prd.py --parent P2P-1220 --prd path/to/TICKET.md \
        [--changes path/to/TICKET-CHANGES.md] [--dry-run] [--yes]

Credentials resolve as the adapter's load_creds documents (OS env vars win, then
the Jira MCP env blocks in ~/.claude.json and ~/.codex/config.toml). Nothing
is hardcoded.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# The plugin root's scripts/ holds tracker_api, which resolves the CONFIGURED
# tracker adapter — five directories up from this file
# (scripts/to-ticket/afk/skills/workflow).
_PLUGIN_SCRIPTS = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__)))))), "scripts")
if _PLUGIN_SCRIPTS not in sys.path:
    sys.path.insert(0, _PLUGIN_SCRIPTS)

from tracker_api import load as _load_tracker  # noqa: E402

_tracker = _load_tracker(("FIG_TOKEN", "Jira", "load_creds",
                          "md_to_adf_content", "png_size"))
FIG_TOKEN = _tracker.FIG_TOKEN
Jira = _tracker.Jira
load_creds = _tracker.load_creds
md_to_adf_content = _tracker.md_to_adf_content
png_size = _tracker.png_size

# ----------------------------------------------------------------------------
# Managed-block sentinels. These delimit the region this script owns inside the
# issue description. Edits BETWEEN the markers are overwritten on re-run; edits
# OUTSIDE are preserved verbatim. The text is matched exactly on re-run, so do
# not change it without a migration.
# ----------------------------------------------------------------------------
MARK_START = "afk:prd:start"
MARK_END = "afk:prd:end"
START_NOTE = (
    "  — auto-generated by /afk-toolkit:to-ticket from PRD.md. "
    "Edits between this marker and afk:prd:end are overwritten on re-run; "
    "edit PRD.md and re-run instead."
)
FIG_PREFIX = "afk-fig"  # attachment filenames: afk-fig{N}.png


# ============================================================================
# Mermaid rendering
# ============================================================================
MERMAID_RE = re.compile(r"^[ \t]*```+[ \t]*mermaid[ \t]*\n(.*?)\n[ \t]*```+[ \t]*$",
                        re.DOTALL | re.MULTILINE)


def extract_mermaid(md_text):
    """Replace each ```mermaid block with a lone-paragraph placeholder token.
    Returns (new_md, [mermaid_source, ...]) in document order."""
    blocks = []

    def repl(m):
        idx = len(blocks)
        blocks.append(m.group(1))
        return f"\n\n{FIG_TOKEN.format(idx)}\n\n"

    return MERMAID_RE.sub(repl, md_text), blocks


def render_mermaid(source, out_png):
    """Render a mermaid source string to out_png via mmdc / npx mermaid-cli."""
    with tempfile.NamedTemporaryFile("w", suffix=".mmd", delete=False, encoding="utf-8") as t:
        t.write(source)
        mmd = t.name
    cmds = [
        ["mmdc", "-i", mmd, "-o", out_png, "-b", "white"],
        ["npx", "-y", "@mermaid-js/mermaid-cli", "-i", mmd, "-o", out_png, "-b", "white"],
    ]
    last = None
    for cmd in cmds:
        # Resolve on PATH first. With shell=True on Windows a missing command exits
        # non-zero instead of raising FileNotFoundError, so the CalledProcessError
        # branch below used to break the loop and the npx fallback never ran.
        exe = shutil.which(cmd[0])
        if exe is None:
            last = FileNotFoundError(f"{cmd[0]} is not on PATH")
            continue
        try:
            subprocess.run([exe, *cmd[1:]], check=True, capture_output=True, text=True)
            os.unlink(mmd)
            return out_png
        except subprocess.CalledProcessError as e:
            last = e
            break
    os.unlink(mmd)
    raise RuntimeError(
        "mermaid render failed. Install mermaid-cli (npm i -g @mermaid-js/mermaid-cli) "
        f"or ensure npx can fetch it. Last error: {getattr(last,'stderr',last)}")


# ============================================================================
# Description merge (preserve PO content, manage only the sentinel block)
# ============================================================================
def node_text(node):
    if isinstance(node, dict):
        if node.get("type") == "text":
            return node.get("text", "")
        return "".join(node_text(c) for c in node.get("content", []) or [])
    if isinstance(node, list):
        return "".join(node_text(c) for c in node)
    return ""


def is_start_marker(node):
    return (node.get("type") == "paragraph"
            and node_text(node).strip().startswith(MARK_START))


def is_end_marker(node):
    return (node.get("type") == "paragraph"
            and node_text(node).strip() == MARK_END)


def strip_managed_block(content):
    """Remove [start_marker .. end_marker] inclusive.
    Returns (remainder, insert_index, had_block); insert_index is where the
    block used to be (len(remainder) if absent)."""
    out, i, insert_at = [], 0, None
    while i < len(content):
        if is_start_marker(content[i]):
            insert_at = len(out)
            j = i + 1
            while j < len(content) and not is_end_marker(content[j]):
                j += 1
            i = j + 1  # skip end marker too
            continue
        out.append(content[i])
        i += 1
    return out, (insert_at if insert_at is not None else len(out)), insert_at is not None


PLACEHOLDER_RE = re.compile(r"^(tbd|todo|n/?a|none|see prd|to be (defined|determined)|\.+)$", re.I)


def is_barebone(remainder):
    """Heuristic: True if the non-managed remainder is low-value and safe to absorb."""
    if not remainder:
        return True
    rich = {"table", "mediaSingle", "media", "mediaGroup", "codeBlock", "rule"}
    headings = sum(1 for n in remainder if n.get("type") == "heading")
    list_items = 0
    for n in remainder:
        if n.get("type") in ("bulletList", "orderedList"):
            list_items += len(n.get("content", []) or [])
        if n.get("type") in rich:
            return False
    if headings >= 2 or list_items >= 3:
        return False
    text = node_text(remainder).strip()
    if PLACEHOLDER_RE.fullmatch(text):
        return True
    return len(text) < 200


def marker_paragraph(text):
    return {"type": "paragraph",
            "content": [{"type": "text", "text": text, "marks": [{"type": "em"}]}]}


def build_description(existing_adf, prd_content):
    existing = (existing_adf or {}).get("content", []) if isinstance(existing_adf, dict) else []
    remainder, insert_at, had_block = strip_managed_block(existing)
    managed = [marker_paragraph(MARK_START + START_NOTE), *prd_content, marker_paragraph(MARK_END)]
    if is_barebone(remainder):
        final = managed
        absorbed = bool(remainder)
    elif not had_block:
        # No prior managed block: append at the end, separated by a rule so the
        # PO's content and the generated PRD are visually distinct.
        final = remainder + [{"type": "rule"}] + managed
        absorbed = False
    else:
        # Re-run: drop the managed block back where it was (the separating rule,
        # if any, lives in `remainder` outside the markers and is preserved).
        final = remainder[:insert_at] + managed + remainder[insert_at:]
        absorbed = False
    return {"version": 1, "type": "doc", "content": final}, absorbed, len(remainder), had_block


# ============================================================================
# Main
# ============================================================================
def main():
    ap = argparse.ArgumentParser(description="Publish a PRD.md into a Jira issue (ADF).")
    ap.add_argument("--parent", required=True, help="Jira parent key, e.g. P2P-1220")
    ap.add_argument("--prd", required=True, help="path to PRD.md")
    ap.add_argument("--dry-run", action="store_true",
                    help="convert + plan only; render no diagrams, mutate nothing, print ADF")
    ap.add_argument("--yes", action="store_true", help="skip the confirmation prompt")
    ap.add_argument("--changes",
                    help="markdown file with the requirements delta of a re-publish; "
                         "posted as an issue comment after the description PUT "
                         "(skipped with a warning on a first publish)")
    args = ap.parse_args()

    prd_path = Path(args.prd)
    if not prd_path.exists():
        sys.exit(f"ERROR: PRD not found: {prd_path}")
    md_text = prd_path.read_text(encoding="utf-8")
    md_text, mermaid_blocks = extract_mermaid(md_text)

    changes_adf = None
    if args.changes:
        changes_path = Path(args.changes)
        if not changes_path.exists():
            sys.exit(f"ERROR: changes file not found: {changes_path}")
        changes_text = changes_path.read_text(encoding="utf-8")
        if MERMAID_RE.search(changes_text):
            sys.exit("ERROR: --changes cannot carry mermaid blocks (figures embed in "
                     "descriptions only, not comments) — keep the delta textual.")
        changes_adf = {"version": 1, "type": "doc",
                       "content": md_to_adf_content(changes_text, {})}

    base, email, token = load_creds()
    jira = Jira(base, email, token)

    # Fetch existing description + attachments first (also validates the parent + type).
    issue = jira.get_issue(args.parent, "summary,issuetype,description,attachment")
    itype = issue["fields"]["issuetype"]["name"]
    if itype not in ("Enhancement", "Story", "Bug"):
        sys.exit(f"ERROR: parent {args.parent} is a {itype!r}; expected Enhancement, Story or Bug.")
    existing_desc = issue["fields"].get("description")
    existing_atts = issue["fields"].get("attachment", []) or []

    fig_nodes = {}  # placeholder idx -> [mediaSingle node]
    if args.dry_run:
        for idx in range(len(mermaid_blocks)):
            fig_nodes[idx] = [{"type": "paragraph", "content": [
                {"type": "text", "text": f"[dry-run: mermaid figure {idx+1} would render+attach here]",
                 "marks": [{"type": "em"}]}]}]
    else:
        # Replace prior afk-fig* attachments so re-runs don't pile up.
        fig_re = re.compile(rf"^{re.escape(FIG_PREFIX)}\d+\.png$")
        for a in existing_atts:
            if fig_re.match(a.get("filename", "")):
                jira.delete_attachment(a["id"])
        with tempfile.TemporaryDirectory() as td:
            for idx, src in enumerate(mermaid_blocks):
                png = os.path.join(td, f"{FIG_PREFIX}{idx+1}.png")
                render_mermaid(src, png)
                size = png_size(png) or (800, 600)
                att_id = jira.upload_attachment(args.parent, png)
                media_uuid = jira.resolve_media_uuid(att_id)
                fig_nodes[idx] = [{
                    "type": "mediaSingle", "attrs": {"layout": "center"},
                    "content": [{"type": "media", "attrs": {
                        "type": "file", "id": media_uuid, "collection": "",
                        "width": size[0], "height": size[1]}}],
                }]
                print(f"  figure {idx+1}: attached {FIG_PREFIX}{idx+1}.png "
                      f"({size[0]}x{size[1]}) -> media {media_uuid}")

    prd_content = md_to_adf_content(md_text, fig_nodes)
    new_desc, absorbed, kept, republish = build_description(existing_desc, prd_content)

    if changes_adf and not republish:
        print("WARNING: --changes given but no prior managed block on the ticket "
              "(first publish) — no delta to record, comment will be skipped.")
        changes_adf = None

    print(f"\nparent      : {args.parent} ({itype}) — {issue['fields']['summary']}")
    print(f"PRD source  : {prd_path}")
    print(f"action      : {'re-publish (managed block replaced)' if republish else 'first publish'}")
    print(f"diagrams    : {len(mermaid_blocks)}")
    print(f"existing PO : {'absorbed (barebone)' if absorbed else f'{kept} node(s) preserved'}")
    print(f"ADF blocks  : {len(new_desc['content'])}")
    print(f"changes     : {'comment planned from ' + args.changes if changes_adf else 'none'}")

    if args.dry_run:
        out = prd_path.with_suffix(".adf.json")
        out.write_text(json.dumps(new_desc, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"\n[dry-run] wrote ADF to {out} — nothing mutated.")
        if changes_adf:
            cout = changes_path.with_suffix(".adf.json")
            cout.write_text(json.dumps(changes_adf, indent=2, ensure_ascii=False),
                            encoding="utf-8")
            print(f"[dry-run] wrote comment ADF to {cout}")
        return

    if not args.yes:
        ans = input("\nPUT this description to the issue? [y/N] ").strip().lower()
        if ans != "y":
            sys.exit("aborted.")
    jira.update_description(args.parent, new_desc)
    print(f"\nDONE: {args.parent} description updated.")
    if changes_adf:
        cid = jira.add_comment(args.parent, changes_adf)
        print(f"DONE: requirements-delta comment posted (id {cid}).")


if __name__ == "__main__":
    main()
